PREFIX vocabulary1:   <http://opencaesar.io/if-compat/vocabulary/vocabulary1#>

SELECT ?pi ?type

WHERE {
  ?pi a vocabulary1:ProviderInterface ;
  	  vocabulary1:hasInterfaceType ?type .
  NOT EXISTS {
  	?ci vocabulary1:isCompatibleWith ?pi .
  }
}
