PREFIX mission:       <http://imce.jpl.nasa.gov/foundation/mission#>
PREFIX vocabulary1:   <http://opencaesar.io/if-compat/vocabulary/vocabulary1#>

SELECT ?p1 ?p2

WHERE {
  ?p1 a vocabulary1:Platform .
  ?p2 a vocabulary1:Platform .
  ?p1 vocabulary1:isCompatibleWith ?p2 .
  FILTER (STR(?p1) < STR(?p2))
}
ORDER BY ?p1 ?p2
